.rultor.yml
pom.xml

Publish project to sonatype repo (iteration 3 - )

---

src/main/java/com/github/dgroup/dockertest/Logo.java
src/main/java/com/github/dgroup/dockertest/cmd/Arg.java
src/main/java/com/github/dgroup/dockertest/concurrent/Concurrent.java
src/main/java/com/github/dgroup/dockertest/hamcrest/ItemsEndsWith.java

Publish project to sonatype repo (iteration 4 - )

---

.rultor.yml

#122: Copy private key to the rultor build

---

.rultor.yml
.travis.yml

#122: Encrypt rultor assets

---

.rultor.yml

#122: Move `gpg.homedir` to rultor descriptor

---

.rultor.yml

#122: Use decrypted credentials during rultor build

---

.rultor.yml

#122: Use decrypted credentials during rultor build for new email

---

.rultor.yml

#122: Use 'secring.gpg' instead of 'pubring.gpg'

---

.rultor.yml

#122: Use 'secring.gpg' and 'pubring.gpg'

---

.rultor.yml
pom.xml

#122: Release *.jar artifacts to Github release and OSSRH

---

pom.xml

#122: Rename github artifact to ${project.artifactId} 

---

readme.md

For now mvn repository is unstable and have invalid obsolete structure.
Maven Central has no opportunity to remove the artifacts, so, we have to increase the version to `1.0.3`

Release 1.0.2

---

.rultor.yml
pom.xml
readme.md

Merge #152 to master

---

pom.xml
src/main/java/com/github/dgroup/dockertest/concurrent/Concurrent.java
src/main/java/com/github/dgroup/dockertest/yml/tag/YmlTag.java
src/main/java/com/github/dgroup/dockertest/yml/tag/YmlTagEnvelope.java
src/test/java/com/github/dgroup/dockertest/YmlResource.java

#154: Define the scope

---

pom.xml

#154: Fix 0pdd puzzle

---

pom.xml
src/main/java/com/github/dgroup/dockertest/test/output/std/MsgFailed.java
src/main/java/com/github/dgroup/dockertest/yml/tag/Tag.java
src/main/java/com/github/dgroup/dockertest/yml/tag/YmlTag.java
src/main/java/com/github/dgroup/dockertest/yml/tag/YmlTagOutputPredicate.java
src/main/java/com/github/dgroup/dockertest/yml/tag/YmlTagTest.java
src/test/java/com/github/dgroup/dockertest/AppTest.java
src/test/java/com/github/dgroup/dockertest/test/output/std/MsgFailedTest.java
src/test/java/com/github/dgroup/dockertest/test/output/std/StdOutputOfTest.java
src/test/java/com/github/dgroup/dockertest/yml/tag/YmlTagTestsTest.java

#161: The YmlTag should inherit Tag

---

pom.xml
src/main/java/com/github/dgroup/dockertest/hamcrest/False.java
src/main/java/com/github/dgroup/dockertest/hamcrest/True.java
src/main/java/com/github/dgroup/dockertest/yml/tag/TextTag.java
src/test/java/com/github/dgroup/dockertest/AppTest.java
src/test/java/com/github/dgroup/dockertest/yml/YamlSmokeTest.java
src/test/java/com/github/dgroup/dockertest/yml/tag/YmlTagTestsTest.java
src/test/resources/yml/3rd-party-tests/with-single-test.yml

#173: Use domain objects in order to parse YML files

---

readme.md

#171: Badges cleanup

---

pom.xml
src/main/java/com/github/dgroup/dockertest/Logo.java
src/main/java/com/github/dgroup/dockertest/cmd/scalar/ArgAt.java
src/main/java/com/github/dgroup/dockertest/io/Property.java
src/main/java/com/github/dgroup/dockertest/process/output/TimedCmdOutput.java
src/main/java/com/github/dgroup/dockertest/test/output/std/StdOutput.java
src/test/java/com/github/dgroup/dockertest/cmd/ContainerNameTest.java
src/test/java/com/github/dgroup/dockertest/cmd/scalar/ArgInTest.java
src/test/java/com/github/dgroup/dockertest/scalar/StrictIfTest.java
src/test/java/com/github/dgroup/dockertest/yml/YamlSmokeTest.java

#202 Rename the "Docker testing tool" to "Docker image testing" and   replace all \n by System.lineseparator 

---

src/main/java/com/github/dgroup/dockertest/App.java
src/main/java/com/github/dgroup/dockertest/yml/Tag.java
src/main/java/com/github/dgroup/dockertest/yml/Tags.java
src/main/java/com/github/dgroup/dockertest/yml/TgOutputPredicate.java
src/main/java/com/github/dgroup/dockertest/yml/TgTest.java
src/main/java/com/github/dgroup/dockertest/yml/UncheckedYmlFormatException.java
src/main/java/com/github/dgroup/dockertest/yml/YmlFormatException.java
src/main/java/com/github/dgroup/dockertest/yml/tag/TagsOf.java
src/main/java/com/github/dgroup/dockertest/yml/tag/TgEnvelope.java
src/main/java/com/github/dgroup/dockertest/yml/tag/UncheckedTag.java
src/main/java/com/github/dgroup/dockertest/yml/tag/UncheckedTags.java
src/main/java/com/github/dgroup/dockertest/yml/tag/output/TgOutputPredicateOf.java
src/main/java/com/github/dgroup/dockertest/yml/tag/output/TgPredicateFake.java
src/main/java/com/github/dgroup/dockertest/yml/tag/test/TgTestOf.java
src/main/java/com/github/dgroup/dockertest/yml/tag/test/UncheckedTgTest.java
src/test/java/com/github/dgroup/dockertest/YmlResource.java
src/test/java/com/github/dgroup/dockertest/yml/TagsOfTest.java
src/test/java/com/github/dgroup/dockertest/yml/tag/TagOutputTest.java
src/test/java/com/github/dgroup/dockertest/yml/tag/TagTestsTest.java
src/test/java/com/github/dgroup/dockertest/yml/tag/TagVersionTest.java
src/test/java/com/github/dgroup/dockertest/yml/tag/TgTestOfTest.java

#191 IllegalYmlFormatException.java:36: Rename to YmlFormatException

---

pom.xml

#218 Downgrade the version from pom.xml to 1.0.4. The version 1.1.0 will be set to pom.xml during CD process automatically

---

pom.xml
src/main/java/com/github/dgroup/dockertest/Logo.java
src/main/java/com/github/dgroup/dockertest/text/highlighted/BlueText.java

#226: DepShield transitive vulnerabilities from 'docker-java' lib

---

.travis.yml

#245: NotFoundException: {"message":"No such image: alpine:latest"}

---

pom.xml
run.sh
src/main/java/com/github/dgroup/dockertest/concurrent/Concurrent.java
src/main/java/com/github/dgroup/dockertest/process/docker/cmd/Pull.java
src/test/java/com/github/dgroup/dockertest/AppTest.java
src/test/java/com/github/dgroup/dockertest/Scenario.java
src/test/java/com/github/dgroup/dockertest/ScenarioOf.java
src/test/java/com/github/dgroup/dockertest/process/docker/cmd/PullTest.java
src/test/java/com/github/dgroup/dockertest/process/docker/cmd/package-info.java
src/test/resources/yml/regression/issue242.yml

#242: NotModifiedException for simple test

---

.editorconfig
pom.xml
readme.md
run.sh

#241 
-----
[View rendered readme.md](https://github.com/dgroup/docker-unittests/blob/241/readme.md)

#241: No install/download section

---

.rultor.yml

#251: Release shaded jar once rultor creates the release

---

.rultor.yml

#251: Update & push project version

---

.rultor.yml

 #251: Print tag to the output
